// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFgbnFRik7o5hdJmtrj7c2-szlscYpXDE',
    appId: '1:810716670322:web:3f9411040f95f5141495eb',
    messagingSenderId: '810716670322',
    projectId: 'flutterapp-fcd3f',
    authDomain: 'flutterapp-fcd3f.firebaseapp.com',
    storageBucket: 'flutterapp-fcd3f.appspot.com',
    measurementId: 'G-RHRHGNPHFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj1YXrhlPnwhIJCpQFQXUgiVRENq_GJEE',
    appId: '1:810716670322:android:08a82b1cdf91a3bf1495eb',
    messagingSenderId: '810716670322',
    projectId: 'flutterapp-fcd3f',
    storageBucket: 'flutterapp-fcd3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ_lgZbwUF6xeBVNxSDBOsLMiWhcuSNVw',
    appId: '1:810716670322:ios:107ffb7cdeb202f31495eb',
    messagingSenderId: '810716670322',
    projectId: 'flutterapp-fcd3f',
    storageBucket: 'flutterapp-fcd3f.appspot.com',
    iosClientId: '810716670322-8m104pk10qfcbfih4v0dteb027kbcpek.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ_lgZbwUF6xeBVNxSDBOsLMiWhcuSNVw',
    appId: '1:810716670322:ios:107ffb7cdeb202f31495eb',
    messagingSenderId: '810716670322',
    projectId: 'flutterapp-fcd3f',
    storageBucket: 'flutterapp-fcd3f.appspot.com',
    iosClientId: '810716670322-8m104pk10qfcbfih4v0dteb027kbcpek.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
